
project_id = "qzykfyavenplpxpdnfxh"

[auth.smtp]
enabled = false
sender_name = "Supabase"
sender_address = "hawa@cs.washington.edu"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public", "supabase_functions"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = false

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = false
port = 54324

[storage]
enabled = true

[search]
enabled = false

[functions]
enabled = true

[vector]
enabled = false

[edge_functions]
enabled = true
