
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzykfyavenplpxpdnfxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6eWtmeWF2ZW5wbHB4cGRuZnhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMzk3NjQsImV4cCI6MjA2MjgxNTc2NH0.fMRSARTizLWE04-zI1v70kwugmlOkM1uwbhYSOgGO4g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Add SQL helper function to Supabase client
// This is a workaround to use SQL expressions in queries
(supabase as any).sql = (strings: string | TemplateStringsArray, ...values: any[]) => {
  if (typeof strings === 'string') {
    return strings;
  }
  
  let result = strings[0];
  for (let i = 0; i < values.length; i++) {
    result += values[i] + strings[i + 1];
  }
  return result;
};
